<?php
// ============================================================
// admin/reports/view.php
// ============================================================

$pageTitle = 'Print Report';

require_once '../../config/db.php';
require_once '../../includes/auth.php';

requireLogin();
requireRole('admin');

$pdo = getDB();

$program_id = $_GET['program_id'] ?? '';
$report_type = $_GET['report_type'] ?? '';

if (!$program_id || !$report_type) {
    die("Invalid request parameters.");
}

// Fetch program details
$stmt = $pdo->prepare("SELECT * FROM scholarship_programs WHERE id = ?");
$stmt->execute([$program_id]);
$program = $stmt->fetch();

if (!$program) {
    die("Program not found.");
}

// Fetch Report Data based on type
$reportData = [];
$reportTitle = "";

if ($report_type === 'ranking') {
    $reportTitle = "Ranking Report";
    $stmt = $pdo->prepare("
        SELECT 
            u.student_code, 
            u.full_name, 
            r.`rank`, 
            r.total_score, 
            r.recommended 
        FROM ranking_results r
        JOIN applications a ON r.application_id = a.id
        JOIN users u ON a.student_id = u.id
        WHERE a.program_id = ?
        ORDER BY r.`rank` ASC
    ");
    $stmt->execute([$program_id]);
    $reportData = $stmt->fetchAll();

} elseif ($report_type === 'disbursement') {
    $reportTitle = "Disbursement Report";
    $stmt = $pdo->prepare("
        SELECT 
            u.student_code, 
            u.full_name, 
            r.`rank`, 
            r.total_score, 
            d.amount, 
            d.status 
        FROM ranking_results r
        JOIN applications a ON r.application_id = a.id
        JOIN users u ON a.student_id = u.id
        LEFT JOIN disbursements d ON a.id = d.application_id
        WHERE a.program_id = ? AND r.recommended = 1
        ORDER BY r.`rank` ASC
    ");
    $stmt->execute([$program_id]);
    $reportData = $stmt->fetchAll();

} elseif ($report_type === 'summary') {
    $reportTitle = "Eligibility Summary";
    $stmt = $pdo->prepare("
        SELECT 
            u.student_code, 
            u.full_name, 
            a.status as app_status, 
            e.is_passed, 
            e.reason 
        FROM applications a
        JOIN users u ON a.student_id = u.id
        LEFT JOIN eligibility_results e ON a.id = e.application_id
        WHERE a.program_id = ?
        ORDER BY a.id ASC
    ");
    $stmt->execute([$program_id]);
    $reportData = $stmt->fetchAll();
} else {
    die("Unknown report type.");
}

// Log the report generation (Optional but good for audit)
$stmtLog = $pdo->prepare("INSERT INTO reports (report_type, generated_by, program_id) VALUES (?, ?, ?)");
$stmtLog->execute([$report_type, $_SESSION['user_id'], $program_id]);

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= e($reportTitle) ?> - <?= e($program['name']) ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background: #fff; color: #333; }
        .report-header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #333; }
        .report-header h1 { font-size: 24px; font-weight: bold; margin-bottom: 5px; }
        .report-header h2 { font-size: 18px; color: #555; }
        .report-meta { display: flex; justify-content: space-between; margin-bottom: 20px; font-size: 14px; }
        .table th { background-color: #f8f9fa !important; -webkit-print-color-adjust: exact; }
        
        @media print {
            .no-print { display: none !important; }
            body { padding: 0; margin: 0; }
            .container { width: 100%; max-width: 100%; padding: 0; }
        }
    </style>
</head>
<body>
    <div class="container py-4">
        <!-- Print Controls -->
        <div class="no-print mb-4 d-flex justify-content-end gap-2">
            <button onclick="window.print()" class="btn btn-primary"><i class="bi bi-printer"></i> Print / Save PDF</button>
            <a href="index.php" class="btn btn-secondary">Back</a>
        </div>

        <!-- Report Header -->
        <div class="report-header">
            <h1>SCHOLARSHIP MANAGEMENT SYSTEM</h1>
            <h2><?= e($reportTitle) ?></h2>
        </div>

        <!-- Report Meta Info -->
        <div class="report-meta">
            <div>
                <strong>Program:</strong> <?= e($program['name']) ?><br>
                <strong>Date Generated:</strong> <?= date('Y-m-d H:i:s') ?>
            </div>
            <div class="text-end">
                <strong>Generated By:</strong> <?= e($_SESSION['user_name'] ?? 'Admin') ?><br>
                <strong>Total Records:</strong> <?= count($reportData) ?>
            </div>
        </div>

        <!-- Report Data Table -->
        <table class="table table-bordered">
            <?php if ($report_type === 'ranking'): ?>
                <thead>
                    <tr>
                        <th width="80">Rank</th>
                        <th>Student Code</th>
                        <th>Full Name</th>
                        <th>Total Score</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($reportData as $row): ?>
                        <tr>
                            <td class="text-center"><strong><?= e($row['rank']) ?></strong></td>
                            <td><?= e($row['student_code']) ?></td>
                            <td><?= e($row['full_name']) ?></td>
                            <td><?= e($row['total_score']) ?></td>
                            <td>
                                <?= $row['recommended'] ? '<span class="text-success fw-bold">Recommended</span>' : '<span class="text-warning text-dark fw-bold">Waiting</span>' ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>

            <?php elseif ($report_type === 'disbursement'): ?>
                <thead>
                    <tr>
                        <th width="80">Rank</th>
                        <th>Student Code</th>
                        <th>Full Name</th>
                        <th>Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($reportData as $row): ?>
                        <tr>
                            <td class="text-center"><strong><?= e($row['rank']) ?></strong></td>
                            <td><?= e($row['student_code']) ?></td>
                            <td><?= e($row['full_name']) ?></td>
                            <td><?= number_format($row['amount'] ?? $program['budget'] / $program['slots'], 2) ?> VND</td>
                            <td><?= ucfirst(e($row['status'] ?? 'Pending')) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>

            <?php elseif ($report_type === 'summary'): ?>
                <thead>
                    <tr>
                        <th>Student Code</th>
                        <th>Full Name</th>
                        <th>App Status</th>
                        <th>Eligibility</th>
                        <th>Reason</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($reportData as $row): ?>
                        <tr>
                            <td><?= e($row['student_code']) ?></td>
                            <td><?= e($row['full_name']) ?></td>
                            <td><?= ucfirst(e($row['app_status'])) ?></td>
                            <td>
                                <?php if ($row['is_passed'] === 1): ?>
                                    <span style="color: green;">Passed</span>
                                <?php elseif ($row['is_passed'] === 0): ?>
                                    <span style="color: red;">Failed</span>
                                <?php else: ?>
                                    <span style="color: gray;">Pending</span>
                                <?php endif; ?>
                            </td>
                            <td><?= e($row['reason'] ?? '-') ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            <?php endif; ?>
        </table>
        
        <?php if (empty($reportData)): ?>
            <div class="text-center py-4 text-muted border border-top-0">
                No data available for this report.
            </div>
        <?php endif; ?>
        
        <div class="mt-5 pt-5 d-flex justify-content-between text-center no-print-page-break">
            <div style="width: 200px; border-top: 1px solid #000; padding-top: 10px;">
                <strong>Prepared By</strong>
            </div>
            <div style="width: 200px; border-top: 1px solid #000; padding-top: 10px;">
                <strong>Approved By</strong>
            </div>
        </div>
    </div>
</body>
</html>
